version: "3.9"
services:
  backend-server:
    build: .
    ports:
      - "5001:5001"
    env_file:
      - ./src/.env
    depends_on:
      - mongo
    networks:
      - backend-net

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge
